name: Run scripts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        day: ['Day1', 'Day2', 'Day3']   # runs each day in parallel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - name: Run all scripts for ${{ matrix.day }}
        run: |
          julia -e '
            using Pkg: Pkg
            cd(joinpath("Tutorials", "${{ matrix.day }}"))
            @show pwd()
            Pkg.activate(".")
            Pkg.instantiate()
            @show readdir()
            files = filter(readdir()) do f
                @show f
                @show isfile(f)
                @show endswith(f, ".jl")
                @show isdigit(f[1])
                @show (f[2] == '-')
                return isfile(f) && endswith(f, ".jl") && isdigit(f[1]) && (f[2] == '-')
            end
            @show files
            for f in files
                println("Running ", f)
                @eval module $(gensym())
                    include($f)
                    main(; outputlevel = 2)
                end
            end'
